### ISSUE TITLE
Support tags of all opened buffers?

### ISSUE THREAD

**Issue by tamlok** [fcying/telescope-ctags-outline.nvim#2]
Could we also support tags outline of all opened buffers?

Thanks!

**Comment by fcying** [comment]
d7c28d776f96513ab09f9d73d2e4b608c9415a64
you can use `require('telescope').extensions.ctags_outline.outline({buf='all'})` get all opened buffers outline.
Currently all buf use current buf's ctags ft_option , 
If each file uses its own ft_option , need to call ctags multiple times, worry about affecting performance.

**Comment by tamlok** [comment]
That is perfect enough as in most cases all buffers should be in the same language. Thaaaaaaaaanks for your quick response!
