### ISSUE TITLE
(Solved) Certain flags do not work (In particular javascript async functions)

### ISSUE THREAD

**Issue by envico801** [fcying/telescope-ctags-outline.nvim#5]
## Issue

The plugin was unable to correctly identify and display async JavaScript functions in the outline. The built-in `--javascript-kinds=f` options did not work as expected. And it only displayed the regular functions

## Cause

The issue was related to the version of Ctags being used. The default Exuberant Ctags binary did not have the necessary support for properly identifying the functions.

## Solution

Just don't use old binaries like me🤦‍♂️

Here are the steps to configure the `telescope-ctags-outline.nvim` plugin to work with Universal Ctags and correctly capture async JavaScript functions:

1. Uninstall the previous version of ctags you have, in my case:

	```sh
	# Uninstall default ctags (Ubuntu)
	sudo apt-get remove --purge exuberant-ctags
	```

2. Install the `universal-ctags` binary on your system. You can do this with your package manager (e.g. `sudo apt-get install universal-ctags` in Ubuntu) or manually [install the nightly version](https://github.com/universal-ctags/ctags-nightly-build). **You may also need to install dependencies**.

After making the changes it should work fine.

**Comment by envico801** [comment]
I'm leaving it here in case the same thing happened to someone else.

**Comment by fcying** [comment]
Thanks for the reminder. I’ll update the doc to highlight this point.
